apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-box
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:freiberg-roman/home-k8s.git"
    path: apps/dev-box
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
