apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/freiberg-roman/home-k8s.git"
    path: apps/docker-registry
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
