apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/freiberg-roman/home-k8s.git"
    path: cluster-addons/nvidia-device-plugin
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvidia-device-plugin
