apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    meta.helm.sh/release-name: nvdp
    meta.helm.sh/release-namespace: nvidia-device-plugin
  labels:
    app.kubernetes.io/instance: nvdp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.18.0
    helm.sh/chart: nvidia-device-plugin-0.18.0
  name: nvdp-nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvdp
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nvdp
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: feature.node.kubernetes.io/cpu-model.vendor_id
                    operator: In
                    values:
                      - NVIDIA
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      containers:
        - command:
            - nvidia-device-plugin
          env:
            - name: MPS_ROOT
              value: /run/nvidia/mps
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.4
          imagePullPolicy: IfNotPresent
          name: nvidia-device-plugin-ctr
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: kubelet-device-plugins-dir
            - mountPath: /dev/shm
              name: mps-shm
            - mountPath: /mps
              name: mps-root
            - mountPath: /var/run/cdi
              name: cdi-root
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      restartPolicy: Always
      runtimeClassName: nvidia
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
          name: kubelet-device-plugins-dir
        - hostPath:
            path: /run/nvidia/mps
            type: DirectoryOrCreate
          name: mps-root
        - hostPath:
            path: /run/nvidia/mps/shm
            type: ""
          name: mps-shm
        - hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
          name: cdi-root
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
