apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    meta.helm.sh/release-name: nvdp
    meta.helm.sh/release-namespace: nvidia-device-plugin
  labels:
    app.kubernetes.io/instance: nvdp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/version: 0.18.0
    helm.sh/chart: nvidia-device-plugin-0.18.0
  name: nvdp-nvidia-device-plugin-mps-control-daemon
  namespace: nvidia-device-plugin
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvdp
      app.kubernetes.io/name: nvidia-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nvdp
        app.kubernetes.io/name: nvidia-device-plugin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: feature.node.kubernetes.io/cpu-model.vendor_id
                    operator: In
                    values:
                      - NVIDIA
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
      containers:
        - command:
            - mps-control-daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.0
          imagePullPolicy: IfNotPresent
          name: mps-control-daemon-ctr
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /dev/shm
              name: mps-shm
            - mountPath: /mps
              name: mps-root
      dnsPolicy: ClusterFirst
      hostPID: true
      initContainers:
        - command:
            - mps-control-daemon
            - mount-shm
          image: nvcr.io/nvidia/k8s-device-plugin:v0.18.0
          imagePullPolicy: IfNotPresent
          name: mps-control-daemon-mounts
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mps
              mountPropagation: Bidirectional
              name: mps-root
      nodeSelector:
        nvidia.com/mps.capable: "true"
      priorityClassName: system-node-critical
      restartPolicy: Always
      runtimeClassName: nvidia
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - hostPath:
            path: /run/nvidia/mps
            type: DirectoryOrCreate
          name: mps-root
        - hostPath:
            path: /run/nvidia/mps/shm
            type: ""
          name: mps-shm
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
